### ISSUE TITLE
can not find my GPU

### ISSUE THREAD

**Issue by Fs2qFtoS** [ofeksadlo/CSGO-Aimbot-CNN#15]
Hello, there
i am trying to run this program on conda with python 3.7.7
and i install the package followed the requirement provided by the requirement.txt
However, when i am trying to run aimbot.py, i got this problem.

(CSGO) C:\Users\xuyic\Downloads\CSGO-Aimbot-CNN-main2\CSGO-Aimbot-CNN-main>python aimbotTensorflow.py
WARNING:tensorflow:From aimbotTensorflow.py:122: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

W1206 23:46:17.620855 12980 module_wrapper.py:139] From aimbotTensorflow.py:122: The name tf.keras.backend.get_session is deprecated. Please use tf.compat.v1.keras.backend.get_session instead.

2021-12-06 23:46:17.695702: I tensorflow/core/common_runtime/dml/dml_device_factory.cc:45] DirectML device enumeration: found 2 compatible adapters.
2021-12-06 23:46:17.696097: I tensorflow/core/platform/cpu_feature_guard.cc:142] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2
2021-12-06 23:46:17.700816: I tensorflow/core/common_runtime/dml/dml_device_factory.cc:32] DirectML: creating device on adapter 0 (AMD Radeon(TM) Graphics)
2021-12-06 23:46:17.763293: I tensorflow/stream_executor/platform/default/dso_loader.cc:60] Successfully opened dynamic library DirectMLba106a7c621ea741d2159d8708ee581c11918380.dll
2021-12-06 23:46:17.768203: I tensorflow/core/common_runtime/dml/dml_device_factory.cc:32] DirectML: creating device on adapter 1 (NVIDIA GeForce GTX 1650)
Traceback (most recent call last):
  File "aimbotTensorflow.py", line 164, in <module>
    app.run(main)
  File "C:\Users\xuyic\anaconda3\envs\CSGO\lib\site-packages\absl\app.py", line 312, in run
    _run_main(main, args)
  File "C:\Users\xuyic\anaconda3\envs\CSGO\lib\site-packages\absl\app.py", line 258, in _run_main
    sys.exit(main(argv))
  File "aimbotTensorflow.py", line 127, in main
    tf.config.experimental.set_memory_growth(physical_devices[0], True)
  File "C:\Users\xuyic\anaconda3\envs\CSGO\lib\site-packages\tensorflow_core\python\framework\config.py", line 454, in set_memory_growth
    context.context().set_memory_growth(device, enable)
  File "C:\Users\xuyic\anaconda3\envs\CSGO\lib\site-packages\tensorflow_core\python\eager\context.py", line 1215, in set_memory_growth
    raise ValueError("Cannot set memory growth on non-GPU devices")
ValueError: Cannot set memory growth on non-GPU devices

This error already shows my computer have GTX1650, but the final value tells me ValueError: Cannot set memory growth on non-GPU devices.

May i get some idea from you

**Comment by Fs2qFtoS** [comment]
By the way, i can run the main.py but it doesn't work.
I guess this is related to my screen resolution (i am 2560*1600) but it still doesn't work when i change the height and width both in the main.py and CSGO to 2560 and 1600

**Comment by ofeksadlo** [comment]
I've never tested on any other resolution other than 1920x1080
I wouldn't even try to use any other resolution.
The dataset I trained the model is for 1920x1080 images.
And beyond that the dataset is quite out-dated.

In order to make it work for you I would try to use 1920x1080 with black bars fullscreen windowed
and run cs:go.
It may work.

**Comment by Fs2qFtoS** [comment]
okay, got it and thank you it do works when i use resolution 1920*1080
Hey, dude, this project is so coooooooooool!
