### ISSUE TITLE
Hi 2021-12-18 12:17:06.935952: I tensorflow/core/

### ISSUE THREAD

**Issue by miguel-leal** [ofeksadlo/CSGO-Aimbot-CNN#20]
2021-12-18 12:17:06.935952: I tensorflow/core/common_runtime/dml/dml_device_factory.cc:45] DirectML device enumeration: found 2 compatible adapters.
You have a compatible GPU for beta tensorflow aimbot.
Would you like to launch beta tensorflow aimbot (y = Yes): yes
Launching aimbot on CPU...
Aimbot Enabled
FOV Size: 96x96
Traceback (most recent call last):
  File "C:\Users\MiguelLeal\Downloads\CSGO-Aimbot-CNN-main\CSGO-Aimbot-CNN-main\main.py", line 310, in <module>
    outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "C:\Users\MiguelLeal\Downloads\CSGO-Aimbot-CNN-main\CSGO-Aimbot-CNN-main\main.py", line 310, in <listcomp>
    outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

**Comment by miguel-leal** [comment]
solution https://github.com/ofeksadlo/CSGO-Aimbot-CNN/issues/14#issuecomment-953211908
