### ISSUE TITLE
Script not working

### ISSUE THREAD

**Issue by CrabotY** [ofeksadlo/CSGO-Aimbot-CNN#25]
On startup it gives the following error.

Launching aimbot on CPU...
Aimbot Enabled
FOV Size: 96x96
Traceback (most recent call last):
  File "d:\Робочий стол\CSGO-Aimbot-CNN-main\main.py", line 310, in <module>
    outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
  File "d:\Робочий стол\CSGO-Aimbot-CNN-main\main.py", line 310, in <listcomp>
    outputNames = [layerNames[i[0] - 1] for i in net.getUnconnectedOutLayers()]
IndexError: invalid index to scalar variable.

**Comment by ofeksadlo** [comment]
I can't tell for sure your problem
Did you installed the requirements.txt?
If so I would suggest to debug it.

The trained model is old.
You can train a model yourself of course. But this not
an easy to run "cheat".
It was a learning project from 3 years ago.
