### ISSUE TITLE
not working for me

### ISSUE THREAD

**Issue by kill1504** [ofeksadlo/CSGO-Aimbot-CNN#4]

**Comment by kill1504** [comment]
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Launching aimbot on CPU...
Aimbot Enabled
FOV Size: 160x160

Warning (from warnings module):
  File "C:\Users\divud\Desktop\working hackkz\CSGO-Aimbot-CNN-main\main.py", line 215
    pygame.draw.rect(screen, [0, 255, 0], [screenWidth/2-fovWidth/2, screenHieght/2-fovHeight/2, fovWidth, fovHeight], 1)
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.
Exception in thread Thread-1:
Traceback (most recent call last):
  File "C:\Users\divud\AppData\Local\Programs\Python\Python38\lib\threading.py", line 932, in _bootstrap_inner
    self.run()
  File "C:\Users\divud\AppData\Local\Programs\Python\Python38\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\divud\AppData\Local\Programs\Python\Python38\lib\site-packages\keyboard\__init__.py", line 292, in listen
    _os_keyboard.listen(self.direct_callback)
  File "C:\Users\divud\AppData\Local\Programs\Python\Python38\lib\site-packages\keyboard\_winkeyboard.py", line 560, in listen
    prepare_intercept(callback)
  File "C:\Users\divud\AppData\Local\Programs\Python\Python38\lib\site-packages\keyboard\_winkeyboard.py", line 553, in prepare_intercept
    keyboard_hook = SetWindowsHookEx(WH_KEYBOARD_LL, keyboard_callback, GetModuleHandleW(NULL), NULL)
ctypes.ArgumentError: argument 3: <class 'OverflowError'>: int too long to convert

Warning (from warnings module):
  File "C:\Users\divud\Desktop\working hackkz\CSGO-Aimbot-CNN-main\main.py", line 110
    textRect.center = (x, y)
DeprecationWarning: an integer is required (got type float).  Implicit conversion to integers using __int__ is deprecated, and may be removed in a future version of Python.

**Comment by kill1504** [comment]
thats what i get when i run the python file

**Comment by ofeksadlo** [comment]
I never saw this exception but I did notice you're using python 3.8. 
There is no support for directml-tensorflow for python 3.8. So you should have gotten exception for that as well.
Try to uninstall python 3.8 and install python 3.7.7 then install all dependencies via
requirements.txt and then try running main.py again.

**Comment by kill1504** [comment]
C:\Users\divud>python -m pip install tensorflow-directml
ERROR: Could not find a version that satisfies the requirement tensorflow-directml (from versions: none)
ERROR: No matching distribution found for tensorflow-directml

I got python 3.7.7 and installed all the modules from requirements.txt 
but this last one doesnt want to install with pip 
is there another way?

**Comment by kill1504** [comment]
i managed to download tenserflow with python3 -m pip install --upgrade https://storage.googleapis.com/tensorflow/mac/cpu/tensorflow-1.12.0-py3-none-any.whl

but when i launch main.py i get this error message 


Python 3.7.7 (tags/v3.7.7:d7c567b08f, Mar 10 2020, 09:44:33) [MSC v.1900 32 bit (Intel)] on win32
Type "help", "copyright", "credits" or "license()" for more information.
>>> 
== RESTART: C:\Users\divud\Desktop\working hackkz\CSGO-Aimbot-CNN-main\main.py =
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\divud\Desktop\working hackkz\CSGO-Aimbot-CNN-main\main.py", line 11, in <module>
    import tensorflow as tf
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\__init__.py", line 24, in <module>
    from tensorflow.python import pywrap_tensorflow  # pylint: disable=unused-import
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\__init__.py", line 49, in <module>
    from tensorflow.python import pywrap_tensorflow
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 74, in <module>
    raise ImportError(msg)
ImportError: Traceback (most recent call last):
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 18, in swig_import_helper
    fp, pathname, description = imp.find_module('_pywrap_tensorflow_internal', [dirname(__file__)])
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\imp.py", line 296, in find_module
    raise ImportError(_ERR_MSG.format(name), name=name)
ImportError: No module named '_pywrap_tensorflow_internal'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow.py", line 58, in <module>
    from tensorflow.python.pywrap_tensorflow_internal import *
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 28, in <module>
    _pywrap_tensorflow_internal = swig_import_helper()
  File "C:\Users\divud\AppData\Local\Programs\Python\Python37-32\lib\site-packages\tensorflow\python\pywrap_tensorflow_internal.py", line 20, in swig_import_helper
    import _pywrap_tensorflow_internal
ModuleNotFoundError: No module named '_pywrap_tensorflow_internal'


Failed to load the native TensorFlow runtime.

See https://www.tensorflow.org/install/errors

for some common reasons and solutions.  Include the entire stack trace
above this error message when asking for help.


how can i fix it?

**Comment by kill1504** [comment]
it seems to just be missing ImportError: No module named '_pywrap_tensorflow_internal'
how can i get it

**Comment by ofeksadlo** [comment]
First of all you can't use any tensorflow only the [DirectML tensorflow](https://github.com/microsoft/DirectML/tree/master/TensorFlow).
In order to make the aimbot GPU cross-platform (nvidia and amd) I've used this libary.
Have you completely uninstalled python from your computer?
Because it looks like you're getting entangled with other versions of python
Try uninstalling all python versions on your computer from control panel.
Then install this version of python: [https://www.python.org/downloads/release/python-377/](https://www.python.org/downloads/release/python-377/)
It's the same one as I'm using and should work for you.

Or you could just use the CPU version just open aimbotOnly.py it will lack the drawing on the screen.
But should work for other python versions because there is no use of tensorflow.

**Comment by kill1504** [comment]
i tried the CPU version and it launches. But when I launched a csgo match, it doesnt seem to be working, it just every now and again stares at the floor. But no matter how close i aim or shoot near the head it doesnt do anything
( sorry for the constant spam, I am new to python)

**Comment by ofeksadlo** [comment]
> i tried the CPU version and it launches. But when I launched a csgo match, it doesnt seem to be working, it just every now and again stares at the floor. But no matter how close i aim or shoot near the head it doesnt do anything
> ( sorry for the constant spam, I am new to python)

1) Have you changed the csgo video setting to fullscreen windowed?
2) Have you disabled the mouse raw input in csgo mouse settings?

Because both crucial for the aimbot to work properly.

**Comment by kill1504** [comment]
ok, its working with the CPU 
but for it to be faster and more reliable it needs the tenser flow thing to work on the Gpu right?

I reinstalled my python and got all the modules besides the tenser flow one. 
is there a pip link or something i can use to install it?

**Comment by ofeksadlo** [comment]
> ok, its working with the CPU
> but for it to be faster and more reliable it needs the tenser flow thing to work on the Gpu right?
> 
> I reinstalled my python and got all the modules besides the tenser flow one.
> is there a pip link or something i can use to install it?

Actually the GPU version of the aimbot is still in development and the most stable version currently is the aimbotOnly.py
So after uninstalling any python versions on your pc and installing only this version of python: [https://www.python.org/downloads/release/python-377/](https://www.python.org/downloads/release/python-377/)
You're still getting into trouble installing `pip install tensorflow-directml`?

**Comment by kill1504** [comment]
yes i still get
C:\Users\divud>python -m pip install tensorflow-directml
ERROR: Could not find a version that satisfies the requirement tensorflow-directml (from versions: none)
ERROR: No matching distribution found for tensorflow-directml

**Comment by ofeksadlo** [comment]
This is very strange
Try entering `python --version` in cmd and post what version is printed?

**Comment by kill1504** [comment]
C:\Users\divud>python --version
Python 3.7.7

**Comment by ofeksadlo** [comment]
Well there's only one more reason left that you won't be able to install tensorflow-directml:
Your pip version could be the case mine is pip 20.2.3
So downgrade or upgrade to that version and try installing again.
If that doesn't work then maby your windows os is not supported.

Sadly cross-platform gpu utilization is a nasty business. Most object detection apis support NVIDIA GPU only .
And so as an AMD GPU owner I resort for tensorflow backend which is DirectML.
But chin up currently you're not missing anything but even lower accuracy detections.
Given the tensorflow model is far from bieng accurate and still under development.
Instead I've just updated the main code so you don't need to install tensorflow-directml. To use the main.py
and see drawing on screen.
So if you keep failing to install DirectML just use the updated main.py

**Comment by kill1504** [comment]
It works, even though im averaging 4-6 fps so It cant be used against other players.
Still a very cool concept. And cant wait until it will be on a level where it can be used in competitive matches.

**Comment by ofeksadlo** [comment]
> It works, even though im averaging 4-6 fps so It cant be used against other players.
> Still a very cool concept. And cant wait until it will be on a level where it can be used in competitive matches.

Glad to hear!

**Comment by ofeksadlo** [comment]
I've figured out why you didn't managed to install tensorflow-directml
When you download python you need to download the 64 bit and not 32 bit
<img src='https://i.ibb.co/2hqHz1n/Capture.png' height='320'/>
[https://www.python.org/downloads/release/python-377/](https://www.python.org/downloads/release/python-377/)
Otherwise you'll get `No matching distribution found for tensorflow-directml`
trying to install tensorflow-directml.

**Comment by storm999** [comment]
at least you are having error though. 
I am getting no error but still not working :)
BTW, I had started working on similar protect for my image processing homework before i googled this. 
Mine project is running on GPU. It gives around 60x higher performance (gtx1070 -> 7700HQ)
I stuck on aiming part and wanted to google anyway.

**Comment by ofeksadlo** [comment]
> at least you are having error though.
> I am getting no error but still not working :)
> BTW, I had started working on similar protect for my image processing homework before i googled this.
> Mine project is running on GPU. It gives around 60x higher performance (gtx1070 -> 7700HQ)
> I stuck on aiming part and wanted to google anyway.

You are more than welcome to open an issue.
And I'll do my best to help

**Comment by storm999** [comment]
> > at least you are having error though.
> > I am getting no error but still not working :)
> > BTW, I had started working on similar protect for my image processing homework before i googled this.
> > Mine project is running on GPU. It gives around 60x higher performance (gtx1070 -> 7700HQ)
> > I stuck on aiming part and wanted to google anyway.
> 
> You are more than welcome to open an issue.
> And I'll do my best to help

thank you but, what can we do while there is no error though. What can i report in the new issue

**Comment by ofeksadlo** [comment]
> i

We can start by asking
*  What do you see when you run the main.py
Do you see something like this:
<img src='https://i.ibb.co/gtz8SQ4/Capture1.png' />
Or the window is just closing?

* Did you start CS:GO in full-screen windowed?
* Did you disabled raw mouse input?
* Did you Installed all dependencies from reqiurements.txt file.
* Is your resolution is on 1920x1080?
* Are you on windows environment ?
* Did you tried using [Python 3.7.7 Windows x86-64](https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe)?

**Comment by storm999** [comment]
> > i
> 
> We can start by asking
> 
> * What do you see when you run the main.py
>   Do you see something like this:
> 
> ![](https://camo.githubusercontent.com/df5a544df236fa9e59f8e0776a812eb83bfcbf70b7e97629f5f63893ccd880b7/68747470733a2f2f692e6962622e636f2f67747a385351342f43617074757265312e706e67)
> 
> Or the window is just closing?
> * Did you start CS:GO in full-screen windowed?
> * Did you disabled raw mouse input?
> * Did you Installed all dependencies from reqiurements.txt file.
> * Is your resolution is on 1920x1080?
> * Are you on windows environment ?
> * Did you tried using [Python 3.7.7 Windows x86-64](https://www.python.org/ftp/python/3.7.7/python-3.7.7-amd64.exe)?

All of preliminaries are ensured. (these 6 elements)
I tried cpu version. program runs without any error, seems it just doesnt aim.

**Comment by storm999** [comment]
actually if any installation is missing, would the program run without any error ? I mean maybe issue could be because of a missing component that doesnt cause a visible error maybe ?

**Comment by storm999** [comment]
![csgo_2020-11-28_15-58-13](https://user-images.githubusercontent.com/17099604/100516260-b4e82b80-3193-11eb-91fb-383c47c3e559.png)
![csgo_2020-11-28_15-53-00](https://user-images.githubusercontent.com/17099604/100516273-cb8e8280-3193-11eb-8f63-47d4e3ce23b6.png)
![csgo_2020-11-28_15-53-37](https://user-images.githubusercontent.com/17099604/100516287-d812db00-3193-11eb-86bf-968037ffbec8.png)
maybe you need a better training model.
PS: object names appearing in my pictures are just trivial. They are names of first 4 things in the list I am using.
